window.EQUINOX_LOCATIONS = [
  {
    "id": "the-fern",
    "name": "The Fern",
    "category": "business",
    "categoryLabel": "Business",
    "subtitle": "Cafe/Restaurant",
    "x": -1109.3,
    "y": -1346.19,
    "description": "Player-operated cafe and restaurant.",
    "link": "#"
  },
  {
    "id": "up-n-atom",
    "name": "Up 'N Atom",
    "category": "business",
    "categoryLabel": "Business",
    "subtitle": "Restaurant",
    "x": 85.88,
    "y": 285.61,
    "description": "Restaurant and food service location.",
    "link": "#"
  },
  {
    "id": "pond-cafe",
    "name": "Pond Cafe",
    "category": "business",
    "categoryLabel": "Business",
    "subtitle": "Cafe",
    "x": 1121.79,
    "y": -646.82,
    "description": "Cafe and community business location.",
    "link": "#"
  },
  {
    "id": "light-it-up",
    "name": "Light it Up",
    "category": "business",
    "categoryLabel": "Business",
    "subtitle": "Smoke Shop",
    "x": -1558.68,
    "y": -438.74,
    "description": "Player-operated business location.",
    "link": "#"
  },
  {
    "id": "los-santos-customs",
    "name": "Los Santos Customs",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "subtitle": "Automotive Services",
    "x": -360.24,
    "y": -124.11,
    "description": "Vehicle repair, customization and automotive services.",
    "link": "#"
  },
  {
    "id": "craw-customs",
    "name": "Craw Customs",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "subtitle": "Custom Automotive Shop",
    "x": -686.35,
    "y": -785.94,
    "description": "Player-operated automotive repair and customization shop.",
    "link": "#"
  },
  {
    "id": "bayside",
    "name": "Bayside",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "subtitle": "Automotive Services",
    "x": -1558.68,
    "y": -438.74,
    "description": "Automotive service location.",
    "link": "#"
  },
  {
    "id": "mission-row-pd",
    "name": "Los Santos Police - Mission Row",
    "category": "law-enforcement",
    "categoryLabel": "Law Enforcement",
    "subtitle": "Los Santos Police Department",
    "x": 450.9,
    "y": -1020.6,
    "description": "Mission Row station serving as a primary Los Santos Police Department facility.",
    "link": "https://docs.equinoxroleplay.com/los-santos-police"
  },
  {
    "id": "state-police-chumash",
    "name": "State Police",
    "category": "law-enforcement",
    "categoryLabel": "Law Enforcement",
    "subtitle": "San Andreas State Police",
    "x": -3142.08,
    "y": 1386.73,
    "description": "San Andreas State Police facility serving the Chumash and western highway corridor.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-state-police"
  },
  {
    "id": "general-crafting-grapeseed",
    "name": "General Crafting",
    "category": "crafting",
    "categoryLabel": "Crafting",
    "subtitle": "Grapeseed",
    "x": 1700.7,
    "y": 4788.54,
    "description": "Public general crafting location.",
    "link": "#"
  },
  {
    "id": "general-crafting-south-ls",
    "name": "General Crafting",
    "category": "crafting",
    "categoryLabel": "Crafting",
    "subtitle": "South Los Santos",
    "x": 1473.63,
    "y": -1924.41,
    "description": "Public general crafting location.",
    "link": "#"
  },
  {
    "id": "courthouse",
    "name": "San Andreas Governmental Complex",
    "category": "government",
    "categoryLabel": "Government",
    "subtitle": "Department of Justice",
    "x": -550.1532,
    "y": -196.0362,
    "description": "State courthouse used for judicial proceedings and Department of Justice services.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-district-courts"
  },
  {
    "id": "davis-supermarket",
    "name": "Davis Supermarket",
    "category": "business",
    "categoryLabel": "Business",
    "subtitle": "Grocery Store",
    "x": 53.25,
    "y": -1767.07,
    "description": "Public supermarket serving the Davis area.",
    "link": "#"
  },
  {
    "id": "plastic-surgery",
    "name": "Plastic Surgery",
    "category": "public-service",
    "categoryLabel": "Public Service",
    "subtitle": "Civilian Services",
    "x": -682.26,
    "y": -187.05,
    "description": "Public appearance and cosmetic service location.",
    "link": "#"
  },
  {
    "id": "bolingbroke",
    "name": "Bolingbroke Penitentiary",
    "category": "corrections",
    "categoryLabel": "Corrections",
    "subtitle": "State Correctional Facility",
    "x": 1746.81,
    "y": 2519.49,
    "description": "San Andreas state correctional facility.",
    "link": "#"
  },
  {
    "id": "vespucci-medical",
    "name": "Vespucci Medical",
    "category": "medical",
    "categoryLabel": "Medical",
    "subtitle": "Medical Center",
    "x": -795.21,
    "y": -1222.48,
    "description": "Medical facility serving Vespucci and the western Los Santos area.",
    "link": "#"
  },
  {
    "id": "911-autos",
    "name": "911 Autos",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "subtitle": "Police & EMS Vehicle Dealership",
    "x": -55.99,
    "y": -1096.59,
    "description": "Specialized vehicle dealership for authorized police and emergency-service fleets.",
    "link": "#"
  },
  {
    "id": "luxury-autos",
    "name": "Luxury Autos",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "subtitle": "Luxury & Performance Vehicles",
    "x": -1257.4,
    "y": -369.12,
    "description": "Dealership specializing in luxury and performance vehicles.",
    "link": "#"
  },
  {
    "id": "boat-dealer",
    "name": "Boat Dealer",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "subtitle": "Marine Dealership",
    "x": -739.55,
    "y": -1333.75,
    "description": "Marine dealership for boats and other watercraft.",
    "link": "#"
  },
  {
    "id": "pegasus-enterprises",
    "name": "Pegasus Enterprises",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "subtitle": "Aircraft Dealership",
    "x": -1623.0,
    "y": -3151.56,
    "description": "Aircraft dealership for planes and helicopters.",
    "link": "#"
  },
  {
    "id": "truck-dealer",
    "name": "Truck Dealer",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "subtitle": "Commercial Vehicle Dealership",
    "x": 1214.37,
    "y": -3204.53,
    "description": "Dealership for vans, commercial vehicles and industrial trucks.",
    "link": "#"
  }
];
