window.EQUINOX_LOCATIONS = [
  {
    "id": "the-fern",
    "name": "The Fern",
    "category": "food",
    "categoryLabel": "Food & Drink",
    "icon": "coffee",
    "subtitle": "Cafe & Restaurant",
    "x": -1109.3,
    "y": -1346.19,
    "description": "Player-operated cafe and restaurant.",
    "link": "#"
  },
  {
    "id": "up-n-atom",
    "name": "Up 'N Atom",
    "category": "food",
    "categoryLabel": "Food & Drink",
    "icon": "burger",
    "subtitle": "Restaurant",
    "x": 85.88,
    "y": 285.61,
    "description": "Restaurant and food service location.",
    "link": "#"
  },
  {
    "id": "pond-cafe",
    "name": "Pond Cafe",
    "category": "food",
    "categoryLabel": "Food & Drink",
    "icon": "coffee",
    "subtitle": "Cafe",
    "x": 1123.713,
    "y": -649.492,
    "description": "Cafe and community business location.",
    "link": "#"
  },
  {
    "id": "light-it-up",
    "name": "Light it Up",
    "category": "smoke-shop",
    "categoryLabel": "Smoke Shop",
    "icon": "smoke",
    "subtitle": "Player Business",
    "x": -1558.68,
    "y": -438.74,
    "description": "Player-operated business location.",
    "link": "#"
  },
  {
    "id": "los-santos-customs",
    "name": "Los Santos Customs",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "icon": "wrench",
    "subtitle": "Automotive Services",
    "x": -360.24,
    "y": -124.11,
    "description": "Vehicle repair, customization and automotive services.",
    "link": "#"
  },
  {
    "id": "craw-customs",
    "name": "Craw Customs",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "icon": "wrench",
    "subtitle": "Custom Automotive Shop",
    "x": -686.35,
    "y": -785.94,
    "description": "Player-operated automotive repair and customization shop.",
    "link": "#"
  },
  {
    "id": "bayside",
    "name": "Bayside",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "icon": "wrench",
    "subtitle": "Automotive Services",
    "x": 100.145,
    "y": 6569.512,
    "description": "Automotive service location in northern San Andreas.",
    "link": "#"
  },
  {
    "id": "mission-row-pd",
    "name": "Mission Row Police Department",
    "category": "law-enforcement",
    "categoryLabel": "Law Enforcement",
    "icon": "shield",
    "subtitle": "Los Santos Police Department",
    "x": 450.9,
    "y": -1020.6,
    "description": "Mission Row station serving as a primary Los Santos Police Department facility.",
    "link": "https://docs.equinoxroleplay.com/los-santos-police"
  },
  {
    "id": "state-police-chumash",
    "name": "State Police - Chumash",
    "category": "law-enforcement",
    "categoryLabel": "Law Enforcement",
    "icon": "shield",
    "subtitle": "San Andreas State Police",
    "x": -3142.08,
    "y": 1386.73,
    "description": "San Andreas State Police facility serving the Chumash and western highway corridor.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-state-police"
  },
  {
    "id": "general-crafting-grapeseed",
    "name": "General Crafting North",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "hammer",
    "subtitle": "Grapeseed",
    "x": 1700.7,
    "y": 4788.54,
    "description": "Public general crafting location.",
    "link": "#"
  },
  {
    "id": "general-crafting-south-ls",
    "name": "General Crafting South",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "hammer",
    "subtitle": "South Los Santos",
    "x": 1473.63,
    "y": -1924.41,
    "description": "Public general crafting location.",
    "link": "#"
  },
  {
    "id": "courthouse",
    "name": "Governmental Complex",
    "category": "government",
    "categoryLabel": "Government",
    "icon": "gavel",
    "subtitle": "Department of Justice",
    "x": -550.1532,
    "y": -196.0362,
    "description": "State courthouse used for judicial proceedings and Department of Justice services.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-district-courts"
  },
  {
    "id": "davis-supermarket",
    "name": "Davis Supermarket",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "grocery",
    "subtitle": "Grocery Store",
    "x": 53.25,
    "y": -1767.07,
    "description": "Public supermarket serving the Davis area.",
    "link": "#"
  },
  {
    "id": "plastic-surgery",
    "name": "Plastic Surgery",
    "category": "public",
    "categoryLabel": "Public Service",
    "icon": "scissors",
    "subtitle": "Character Services",
    "x": -682.26,
    "y": -187.05,
    "description": "Public character appearance and cosmetic service location.",
    "link": "#"
  },
  {
    "id": "bolingbroke",
    "name": "Bolingbroke Penitentiary",
    "category": "government",
    "categoryLabel": "Government",
    "icon": "prison",
    "subtitle": "State Correctional Facility",
    "x": 1746.81,
    "y": 2519.49,
    "description": "San Andreas state correctional facility.",
    "link": "https://docs.equinoxroleplay.com/department-of-corrections"
  },
  {
    "id": "vespucci-medical",
    "name": "Vespucci Medical",
    "category": "medical",
    "categoryLabel": "Medical",
    "icon": "medical",
    "subtitle": "Medical Center",
    "x": -795.21,
    "y": -1222.48,
    "description": "Medical facility serving Vespucci and the western Los Santos area.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-medical-services"
  },
  {
    "id": "luxury-autos",
    "name": "Luxury Autos",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "car",
    "subtitle": "Luxury & Performance Vehicles",
    "x": -2213.51,
    "y": -387.47,
    "description": "Dealership specializing in luxury and performance vehicles.",
    "link": "#"
  },
  {
    "id": "boat-dealer",
    "name": "Boat Dealer",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "boat",
    "subtitle": "Marine Dealership",
    "x": -739.55,
    "y": -1333.75,
    "description": "Marine dealership for boats and other watercraft.",
    "link": "#"
  },
  {
    "id": "pegasus-enterprises",
    "name": "Pegasus Enterprises",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "plane",
    "subtitle": "Aircraft Dealership",
    "x": -1623.0,
    "y": -3151.56,
    "description": "Aircraft dealership for planes and helicopters.",
    "link": "#"
  },
  {
    "id": "truck-depot",
    "name": "Trucking Depot",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Commercial Vehicle Job",
    "x": 1208.83,
    "y": -3114.85,
    "description": "Keep the highways truckin.",
    "link": "#"
  },
  {
    "id": "bennys",
    "name": "Benny's Motorworks",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "icon": "wrench",
    "subtitle": "Automotive Services",
    "x": -219.092,
    "y": -1275.0,
    "description": "Vehicle repair, customization and performance services.",
    "link": "#"
  },
  {
    "id": "premium-deluxe-motorsport",
    "name": "Premium Deluxe Motorsport",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "car",
    "subtitle": "Vehicle Dealership",
    "x": -1023.468,
    "y": -1378.659,
    "description": "Public vehicle dealership serving residents of San Andreas.",
    "link": "#"
  },
  {
    "id": "bennys-harmony",
    "name": "Benny's Harmony",
    "category": "mechanic",
    "categoryLabel": "Mechanic",
    "icon": "wrench",
    "subtitle": "Automotive Services",
    "x": 560.147,
    "y": 2785.976,
    "description": "Benny's automotive service location in Harmony.",
    "link": "#"
  },
  {
    "id": "powerplant-county",
    "name": "Powerplant County",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "power",
    "subtitle": "Power Infrastructure",
    "x": 2730.454,
    "y": 1569.512,
    "description": "County power generation and infrastructure site.",
    "link": "#"
  },
  {
    "id": "powerplant-city",
    "name": "Powerplant City",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "power",
    "subtitle": "Power Infrastructure",
    "x": 696.388,
    "y": 130.488,
    "description": "Los Santos power generation and infrastructure site.",
    "link": "#"
  },
  {
    "id": "diamond-casino",
    "name": "Diamond Casino",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "casino",  
    "subtitle": "Casino & Entertainment",
    "x": 959.821,
    "y": 48.171,
    "description": "Casino and entertainment destination in Los Santos.",
    "link": "#"
  },
  {
    "id": "goldline-casino",
    "name": "Goldline Casino",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "casino",
    "subtitle": "Casino & Entertainment",
    "x": 745.656,
    "y": -812.094,
    "description": "Casino and entertainment destination in Los Santos.",
    "link": "#"
  },
  {
    "id": "larrys-used-cars",
    "name": "Larrys Used Cars",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "car",
    "subtitle": "Used Cars",
    "x": 1228.07,
    "y": 2721.61,
    "description": "Purchase or sell your next new(to you) car.",
    "link": "#"
  },
  {
    "id": "911-autos",
    "name": "911 Autos",
    "category": "dealership",
    "categoryLabel": "Dealership",
    "icon": "car",
    "subtitle": "Police & EMS Vehicle Dealership",
    "x": -55.99,
    "y": -1096.59,
    "description": "Specialized vehicle dealership for authorized police and emergency-service fleets.",
    "link": "#"
  },
  {
    "id": "sandy-medical",
    "name": "Sandy Medical",
    "category": "medical",
    "categoryLabel": "Medical",
    "icon": "medical",
    "subtitle": "Medical Center",
    "x": 1833.072,
    "y": 3697.561,
    "description": "Medical facility serving Sandy Shores and the surrounding Blaine County area.",
    "link": "https://docs.equinoxroleplay.com/san-andreas-medical-services"
  },
  {
    "id": "dynasty8",
    "name": "Dynasty 8 Realtors",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "house",
    "subtitle": "Realtor Office",
    "x": -705.52,
    "y": 270.29,
    "description": "The central location to purchase property. Be sure to protect your investments.",
    "link": "#"
  },
  {
    "id": "parsons-rehab",
    "name": "Rehab Facility",
    "category": "government",
    "categoryLabel": "Government",
    "icon": "medical",
    "subtitle": "Rehab Facility",
    "x": -1516.61,
    "y": 849.46,
    "description": "Fight your addiction.",
    "link": "#"
  },
  {
    "id": "oil-rig",
    "name": "Oil Rig Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Oil Rig Job",
    "x": 1395.54,
    "y": -3278.19,
    "description": "Get some easy money.",
    "link": "#"
  },
  {
    "id": "gym",
    "name": "Pump 'N Run",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "dumbbell",
    "subtitle": "Gym for working out",
    "x": -1256.19,
    "y": -351.73,
    "description": "Boost your skills.",
    "link": "#"
  },
  {
    "id": "theme-park",
    "name": "Pier Theme Park",
    "category": "public",
    "categoryLabel": "Public",
    "icon": "ferris-wheel",
    "subtitle": "Theme Park",
    "x": -1708.32,
    "y": -1093.03,
    "description": "Go have some fun at the theme park.",
    "link": "#"
  },
  {
    "id": "window-cleaning",
    "name": "Window Cleaning Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Window Cleaning",
    "x": -1244.14,
    "y": -1240.46,
    "description": "Earn some money cleaning skyscrapers. Don't forget the hardhat.",
    "link": "#"
  },
  {
    "id": "renovation-job",
    "name": "Renovation Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Renovation Job",
    "x": -318.67,
    "y": -2701.54,
    "description": "DIY for other people? Count you in. Don't forget the hardhat.",
    "link": "#"
  },
  {
    "id": "construction-job",
    "name": "Construction Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Construction Job",
    "x": 926.28,
    "y": -1560.18,
    "description": "Build some houses and other structures around LS. Don't forget the hardhat.",
    "link": "#"
  },
  {
    "id": "gruppe-6-job",
    "name": "Gruppe6 Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Gruppe6 Job",
    "x": -6.95,
    "y": -654.5,
    "description": "Drive your armored truck, and refill ATMs or take care of private customers.",
    "link": "#"
  },
  {
    "id": "pizza-delivery-job",
    "name": "Pizza Delivery Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Delivery Job",
    "x": 538.39,
    "y": 101.7,
    "description": "Deliver pizzas to the hungry folk of the state.",
    "link": "#"
  },
  {
    "id": "taxi-job",
    "name": "Taxi Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Delivery Job",
    "x": 895.26,
    "y": -179.05,
    "description": "Deliver the folk of the state to their destination.",
    "link": "#"
  },
  {
    "id": "bus-job",
    "name": "Bus Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Bus Job",
    "x": 450.01,
    "y": -651.14,
    "description": "Drop off the people who rely on public transportation.",
    "link": "#"
  },
  {
    "id": "newspaper-job",
    "name": "Newspaper Delivery Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Delivery Job",
    "x": -599.06,
    "y": -927.98,
    "description": "Throw papers to them old bastards that require a physical read.",
    "link": "#"
  },
  {
    "id": "garbage-job",
    "name": "Garbage Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "Garbage Job",
    "x": -349.2,
    "y": -1569.68,
    "description": "Keep the city and state clean.",
    "link": "#"
  },
  {
    "id": "gopostal-job",
    "name": "GoPostal Job",
    "category": "jobs",
    "categoryLabel": "Jobs",
    "icon": "briefcase",
    "subtitle": "GoPostal Job",
    "x": 133.64,
    "y": 96.23,
    "description": "Deliver packages on time.",
    "link": "#"
  }
];
